#!/usr/bin/env bash

BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( dirname "$BIN_DIR")"

if [[ ! -f /usr/local/bin/composer ]] ; then
    echo "[strata-build-common] [FAIL] Composer is required to build this project.\n"
    exit 500
else
    echo "[strata-build-common] [ OK ] Found Composer on the server.\n"
fi

# Update composer
echo "[strata-build-common] Clearing Composer's cache...\n"
/usr/local/bin/composer clearcache
echo "[strata-build-common] Done\n"

echo "[strata-build-common] Updating Composer...\n"
/usr/local/bin/composer update
echo "[strata-build-common] Done\n"


# Confirm we have all the core dependencies before continuing.
if [[ ! -f $ROOT_DIR/strata ]] ; then
    echo "[strata-build-common] [FAIL] Strata dependency was not installed. Cannot continue.\n"
    exit 500
else
    echo "[strata-build-common] [ OK ] Strata was installed successfuly"
fi


# Create a test database
if [[ -f "$ROOT_DIR/.env" ]] ; then
    echo "[strata-build-common] [ OK ] Found database information. Creating Database..."
    export PATH="$PATH:/usr/bin"
    $ROOT_DIR/strata db create
else
    echo "[strata-build-common] [FAIL] Missing required environment file. Cannot create database and install Wordpress' default tables.\n"
    exit 500
fi

# Create frontend bundle package
echo "[strata-build-common] Running frontend bundle...\n"
export PATH="$PATH:/opt/node-0.12/bin/"
$ROOT_DIR/strata bundle
echo "[strata-build-common] Done\n"

echo "[strata-build-common] Completed successfully."
