#!/usr/bin/env bash

ROOT_DIR=$@

if [[ ! -d ${ROOT_DIR} ]]; then
    echo "[strata-build-common] Missing ROOT_DIR variable. Cannot continue."
    echo "$ROOT_DIR"
    exit 500
fi

# Confirm we have all the core dependencies before continuing.
if [[ ! -f $ROOT_DIR/strata ]] ; then
    echo "[strata-build-common] [FAIL] Strata dependency was not installed. Cannot continue."
    echo $ROOT_DIR/strata
    exit 500
else
    echo "[strata-build-common] [ OK ] Strata was installed successfuly."
fi

# Create a test database
if [[ -f "$ROOT_DIR/.env" ]] ; then
    echo "[strata-build-common] [ OK ] Found database information. Creating Database..."
    export PATH="$PATH:/usr/bin"
    $ROOT_DIR/strata db create
else
    echo "[strata-build-common] [FAIL] Missing required environment file. Cannot create database and install Wordpress' default tables.\n"
    exit 500
fi

# Create frontend bundle package
echo "[strata-build-common] Running frontend bundle...\n"
export PATH="$PATH:/opt/node-0.12/bin/"
$ROOT_DIR/strata bundle
echo "[strata-build-common] Done\n"

echo "[strata-build-common] Completed successfully."

exit 0
