#!/usr/bin/env bash

if [[ ! -f /usr/local/bin/composer ]] ; then
    echo "[strata-build-common] [FAIL] Composer is required to build this project.\n"
    exit 500
else
    echo "[strata-build-common] [ OK ] Found Composer on the server.\n"
fi

# Update composer
echo "[strata-build-common] Clearing Composer's cache...\n"
/usr/local/bin/composer clearcache
echo "[strata-build-common] Done\n"

echo "[strata-build-common] Updating Composer...\n"
/usr/local/bin/composer update
echo "[strata-build-common] Done\n"

exit 0
