#!/usr/bin/env bash

if [[ ! -f /usr/local/bin/composer ]] ; then
    echo "[strata-build-common] [FAIL] Composer is required to build this project.\n"
    echo "$ROOT_DIR"
    exit 500
else
    echo "[strata-build-common] [ OK ] Found Composer on the server.\n"
fi

# Update composer
echo "[strata-build-common] Clearing Composer's cache...\n"
/usr/local/bin/composer clearcache
echo "[strata-build-common] Done\n"

echo "[strata-build-common] Updating Composer...\n"
stdbuf -oL /usr/local/bin/composer update |
  while read -r line;  do
    if [[ $line == *Update\ failed* ]]; then
        exit 500
    fi
    sleep 1
  done
echo "[strata-build-common] Done\n"

exit 0
