#!/usr/bin/env bash

ROOT_DIR=$@

if [[ ! -d ${ROOT_DIR} ]]; then
    echo "[strata-package-common] Missing ROOT_DIR variable. Cannot continue."
    echo "$ROOT_DIR"
    exit 500
fi

echo "[strata-package-common] Removing files from build that are not required..."

# Vendor error:
# This repo generates wierd symlink issues that raise
# errors in Bamboo's JVM
rm -rf ${bamboo_build_working_directory}/vendor/theseer/directoryscanner/tests/_data

# Don't need git
rm -rf ${bamboo_build_working_directory}/.git

# Don't keep the .env
rm ${bamboo_build_working_directory}/.env

# Don't keep the NPM packages
if [[ -d ${bamboo_build_working_directory}/web/app/themes/sage-master/node_modules ]]; then
    rm -rf ${bamboo_build_working_directory}/web/app/themes/sage-master/node_modules
fi

echo "[strata-package-common] Done"


echo "[strata-package-common] Compressing build into release.tar.gz tarball."
cd ..
tar -czvf release.tar.gz -C ${bamboo_build_working_directory} .
mv release.tar.gz ${bamboo_build_working_directory}
echo "[strata-package-common] Done"

echo "[strata-package-common] Refreshing sshd."
sudo service sshd restart
echo "[strata-package-common] Done"

echo "[strata-package-common] Completed successfully."

exit 0
