#!/usr/bin/env bash

BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( dirname "$BIN_DIR")"

# Create a test database config file
if [[ ! -f "$ROOT_DIR/.env" ]] ; then
    echo "[strata-test-common] [ OK ] Found default database information. Copying it to project."
    cp "$ROOT_DIR/.env_empty" "$ROOT_DIR/.env"
    perl -pi -e "s/DB_NAME=/DB_NAME=test_bamboo/g" "$ROOT_DIR/.env"
    perl -pi -e "s/DB_USER=/DB_USER=root/g" "$ROOT_DIR/.env"
    perl -pi -e "s/DB_PASSWORD=/DB_PASSWORD=root/g" "$ROOT_DIR/.env"
    perl -pi -e "s/WP_HOME=/WP_HOME=http:\/\/127\.0\.0\.1:5454/g" "$ROOT_DIR/.env"
    perl -pi -e "s/WP_SITEURL=/WP_SITEURL=http:\/\/127\.0\.0\.1:5454\/wp\//g" "$ROOT_DIR/.env"
else
    echo "[strata-test-common] [SKIP] Did not find default database information. It may not break the build."
fi;


# Build the website
if [[ ! -f $BIN_DIR/build ]] ; then
    echo "[strata-test-common] [FAIL] Cannot find the build script."
    exit 500
else
    echo "[strata-test-common] [ OK ] Found build script. Invoking command...\n"
fi

$BIN_DIR/build

# Run backend tests

if [[ ! -f $ROOT_DIR/strata ]] ; then
    echo "[strata-test-common] [FAIL] Cannot find Strata."
    exit 500
fi

if $ROOT_DIR/strata test; then
    echo "[strata-test-common] [ OK ] Backend tests succeeded."
else
    echo "[strata-test-common] [FAIL] Backend tests failed!" 1>&2
    exit 500
fi

# Run frontend tests
echo "[strata-test-common] [SKIP] Skipping forntend tests."


echo "[strata-test-common] Completed successfully."
