#!/usr/bin/env bash

ROOT_DIR=$@

if [[ -d ${ROOT_DIR} ]]; then
    echo "[strata-package-common] Missing ROOT_DIR variable. Cannot continue."
    echo "$ROOT_DIR"
    exit 500
fi

if [[ ! -f $ROOT_DIR/vendor/iprospect_ca/ip-codebase/src/Bash/Ci/Strata/build-common ]] ; then
    echo "[strata-test-common] [FAIL] Default build script could not be found."
    exit 500
else
    echo "[strata-test-common] [ OK ] Found common build script. Invoking command.."
fi

if sh $ROOT_DIR/vendor/iprospect_ca/ip-codebase/src/Bash/Ci/Strata/build-common; then
    echo "[strata-test-common] [FAIL] Common build passed."
else
    echo "[strata-test-common] [FAIL] Common build failed."
    exit 500
fi


# Run backend tests
# -----------------

if $ROOT_DIR/strata test; then
    echo "[strata-test-common] [ OK ] Backend tests succeeded."
else
    echo "[strata-test-common] [FAIL] Backend tests failed!" 1>&2
    exit 500
fi

# Run frontend tests
# ------------------

echo "[strata-test-common] [SKIP] Skipping forntend tests."

echo "[strata-test-common] Completed successfully."

exit 0
