#!/usr/bin/env bash

ROOT_DIR=$@

if [[ ! -d ${ROOT_DIR} ]]; then
    echo "[strata-test-common] Missing ROOT_DIR variable. Cannot continue."
    echo "$ROOT_DIR"
    exit 500
fi


# Run backend tests
# -----------------

if $ROOT_DIR/strata test; then
    echo "[strata-test-common] [ OK ] Backend tests succeeded."
else
    echo "[strata-test-common] [FAIL] Backend tests failed!" 1>&2
    exit 500
fi

# Run frontend tests
# ------------------

echo "[strata-test-common] [SKIP] Skipping forntend tests."

echo "[strata-test-common] Completed successfully."

exit 0
